"""add tenant_id with default value for existing rows

Revision ID: 20260321_1220_add_tenant_id_default
Revises: b16a14dbc232
Create Date: 2026-03-21 12:20:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260321_1220_add_tenant_id_default"
down_revision: Union[str, None] = "b16a14dbc232"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a default tenant if it doesn't exist
    # We'll check by trying to insert and ignore if it fails due to unique constraint
    # But note: we are in a migration and we don't want to fail if it already exists.
    # We'll use a raw SQL statement to insert if not exists.
    # However, SQLite doesn't have INSERT IGNORE until version 3.24.0, and we don't know the version.
    # Instead, we can do:
    #   INSERT INTO tenants (id, name, subdomain, api_key, is_active, subscription_tier, created_at, updated_at)
    #   SELECT 1, 'Default Tenant', 'default', 'default-api-key-change-in-production', 1, 'free', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
    #   WHERE NOT EXISTS (SELECT 1 FROM tenants WHERE id = 1);
    op.execute("""
        INSERT INTO tenants (id, name, subdomain, api_key, is_active, subscription_tier, created_at, updated_at)
        SELECT 1, 'Default Tenant', 'default', 'default-api-key-change-in-production', 1, 'free', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
        WHERE NOT EXISTS (SELECT 1 FROM tenants WHERE id = 1);
    """)

    # List of tables that need the tenant_id column
    tables = [
        "blocklist_entries",
        "blocklist_sources",
        "blocklist_stats",
        "domains",
        "features",
        "feedback",
        "metadata",
        "temporal_patterns",
        "tld_reputation",
    ]

    for table in tables:
        # Add the tenant_id column with a default value of 1 and not nullable
        # Using batch mode for SQLite compatibility
        with op.batch_alter_table(table) as batch_op:
            batch_op.add_column(
                sa.Column("tenant_id", sa.Integer(), nullable=False, server_default="1")
            )

    # Create indexes for the new tenant_id columns
    # We'll create the indexes that we need for performance
    op.create_index(
        "idx_blocklist_tenant_domain", "blocklist_entries", ["tenant_id", "domain"], unique=False
    )
    op.create_index("idx_blocklist_tenant_id", "blocklist_entries", ["tenant_id"], unique=False)
    op.create_index(
        "idx_blocklist_source_tenant_id", "blocklist_sources", ["tenant_id"], unique=False
    )
    op.create_index(
        "idx_blocklist_source_tenant_name", "blocklist_sources", ["tenant_id", "name"], unique=True
    )
    op.create_index("idx_blocklist_stats_tenant_id", "blocklist_stats", ["tenant_id"], unique=False)
    op.create_index("idx_domains_tenant_domain", "domains", ["tenant_id", "domain"], unique=True)
    op.create_index("idx_domains_tenant_id", "domains", ["tenant_id"], unique=False)
    op.create_index("idx_features_tenant_id", "features", ["tenant_id"], unique=False)
    op.create_index("idx_feedback_tenant_id", "feedback", ["tenant_id"], unique=False)
    op.create_index("idx_metadata_tenant_id", "metadata", ["tenant_id"], unique=False)
    # For temporal_patterns, we need to adjust the index on hour_of_day and day_of_week to be non-unique and add a composite index with tenant_id
    op.drop_index("idx_temporal_hour_day", table_name="temporal_patterns")
    op.create_index(
        "idx_temporal_hour_day", "temporal_patterns", ["hour_of_day", "day_of_week"], unique=False
    )
    op.create_index(
        "idx_temporalpattern_tenant_hour_day",
        "temporal_patterns",
        ["tenant_id", "hour_of_day", "day_of_week"],
        unique=True,
    )
    op.create_index(
        "idx_temporalpattern_tenant_id", "temporal_patterns", ["tenant_id"], unique=False
    )
    op.create_index("idx_tld_reputation_tenant_id", "tld_reputation", ["tenant_id"], unique=False)
    op.create_index(
        "idx_tld_reputation_tenant_tld", "tld_reputation", ["tenant_id", "tld"], unique=True
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes in reverse order
    op.drop_index(op.f("ix_tld_reputation_tenant_id"), table_name="tld_reputation")
    op.drop_index("idx_tld_reputation_tenant_tld", table_name="tld_reputation")
    op.drop_index("idx_tld_reputation_tenant_id", table_name="tld_reputation")
    op.drop_column("tld_reputation", "tenant_id")

    op.drop_index(op.f("ix_temporal_patterns_tenant_id"), table_name="temporal_patterns")
    op.drop_index("idx_temporalpattern_tenant_id", table_name="temporal_patterns")
    op.drop_index("idx_temporalpattern_tenant_hour_day", table_name="temporal_patterns")
    op.drop_index("idx_temporal_hour_day", table_name="temporal_patterns")
    op.create_index(
        op.f("ix_temporal_hour_day"), "temporal_patterns", ["hour_of_day", "day_of_week"], unique=1
    )
    op.drop_column("temporal_patterns", "tenant_id")

    op.drop_index(op.f("ix_metadata_tenant_id"), table_name="metadata")
    op.drop_index("idx_metadata_tenant_id", table_name="metadata")
    op.drop_index("idx_metadata_domain_id", table_name="metadata")
    op.alter_column(
        "metadata",
        "client",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "metadata",
        "rule",
        existing_type=sa.String(length=500),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "metadata",
        "reason",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column("metadata", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_column("metadata", "tenant_id")

    op.drop_index(op.f("ix_feedback_tenant_id"), table_name="feedback")
    op.drop_index("idx_feedback_tenant_id", table_name="feedback")
    op.drop_column("feedback", "tenant_id")

    op.drop_index(op.f("ix_features_tenant_id"), table_name="features")
    op.drop_index("idx_features_tenant_id", table_name="features")
    op.drop_index("idx_features_domain_id", table_name="features")
    op.alter_column("features", "non_alphanumeric", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "features", "vowel_ratio", existing_type=sa.Float(), type_=sa.REAL(), nullable=True
    )
    op.alter_column(
        "features", "digit_ratio", existing_type=sa.Float(), type_=sa.REAL(), nullable=True
    )
    op.alter_column("features", "length", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("features", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_column("features", "tenant_id")

    op.drop_index(op.f("ix_domains_tenant_id"), table_name="domains")
    op.drop_index("idx_domains_tenant_id", table_name="domains")
    op.drop_index("idx_domains_tenant_domain", table_name="domains")
    op.drop_index("idx_domains_risk_score", table_name="domains")
    op.drop_index("idx_domains_is_anomaly", table_name="domains")
    op.drop_index("idx_domains_domain", table_name="domains")
    op.drop_index("idx_domains_created_at", table_name="domains")
    op.drop_index("idx_domains_category", table_name="domains")
    op.alter_column(
        "domains",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "domains", "timestamp", existing_type=sa.DateTime(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "domains", "anomaly_score", existing_type=sa.Float(), type_=sa.REAL(), nullable=True
    )
    op.alter_column(
        "domains", "is_anomaly", existing_type=sa.Boolean(), type_=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "domains",
        "summary",
        existing_type=sa.String(length=2000),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "domains", "category", existing_type=sa.String(length=50), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "domains", "risk_score", existing_type=sa.String(length=20), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "domains", "entropy", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "domains",
        "domain",
        existing_type=sa.String(length=253),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column("domains", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_column("domains", "tenant_id")

    op.drop_index(op.f("ix_blocklist_stats_tenant_id"), table_name="blocklist_stats")
    op.drop_index("idx_blocklist_stats_tenant_id", table_name="blocklist_stats")
    op.drop_column("blocklist_stats", "tenant_id")

    op.drop_index(op.f("ix_blocklist_sources_tenant_id"), table_name="blocklist_sources")
    op.drop_index("idx_blocklist_source_tenant_name", table_name="blocklist_sources")
    op.drop_index("ix_blocklist_sources_tenant_id", table_name="blocklist_sources")
    op.drop_column("blocklist_sources", "tenant_id")

    op.drop_index(op.f("ix_blocklist_entries_tenant_id"), table_name="blocklist_entries")
    op.drop_index("idx_blocklist_tenant_id", table_name="blocklist_entries")
    op.drop_index("idx_blocklist_tenant_domain", table_name="blocklist_entries")
    op.create_index(
        op.f("ix_blocklist_entries_domain"), "blocklist_entries", ["domain"], unique=False
    )
    op.drop_column("blocklist_entries", "tenant_id")

    # Note: We are not dropping the default tenant because it might be in use.
    # If you want to remove it, you can uncomment the following lines:
    # op.delete('tenants').where(tenants.c.id == 1)
    # op.drop_table('tenants')
    # But we are not doing that in the downgrade for safety.

    # ### end Alembic commands ###
