"""add multi-tenancy with default tenant

Revision ID: 1e70097d58ad
Revises: b16a14dbc232
Create Date: 2026-03-21 12:14:08.032392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e70097d58ad"
down_revision: Union[str, None] = "b16a14dbc232"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create tenants table
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("subdomain", sa.String(length=50), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("subscription_tier", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_api_key"), "tenants", ["api_key"], unique=True)
    op.create_index(op.f("ix_tenants_subdomain"), "tenants", ["subdomain"], unique=True)

    # Add tenant_id columns as nullable first with a default value
    op.add_column("blocklist_entries", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("blocklist_sources", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("blocklist_stats", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("domains", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("features", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("feedback", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("metadata", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("temporal_patterns", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("tld_reputation", sa.Column("tenant_id", sa.Integer(), nullable=True))

    # Create a default tenant for existing data
    op.execute(
        "INSERT INTO tenants (id, name, subdomain, api_key, is_active, subscription_tier, created_at, updated_at) VALUES (1, 'Default Tenant', 'default', 'default-api-key-change-in-production', true, 'free', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
    )

    # Set all existing rows to use the default tenant (id=1)
    op.execute("UPDATE blocklist_entries SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.execute("UPDATE blocklist_sources SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.execute("UPDATE blocklist_stats SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.execute("UPDATE domains SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.execute("UPDATE features SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.execute("UPDATE feedback SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.execute("UPDATE metadata SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.execute("UPDATE temporal_patterns SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.execute("UPDATE tld_reputation SET tenant_id = 1 WHERE tenant_id IS NULL")

    # Now make the columns NOT NULL
    op.alter_column("blocklist_entries", "tenant_id", nullable=False)
    op.alter_column("blocklist_sources", "tenant_id", nullable=False)
    op.alter_column("blocklist_stats", "tenant_id", nullable=False)
    op.alter_column("domains", "tenant_id", nullable=False)
    op.alter_column("features", "tenant_id", nullable=False)
    op.alter_column("feedback", "tenant_id", nullable=False)
    op.alter_column("metadata", "tenant_id", nullable=False)
    op.alter_column("temporal_patterns", "tenant_id", nullable=False)
    op.alter_column("tld_reputation", "tenant_id", nullable=False)

    # Add indexes and constraints
    op.create_index(
        "idx_blocklist_tenant_domain", "blocklist_entries", ["tenant_id", "domain"], unique=False
    )
    op.create_index("idx_blocklist_tenant_id", "blocklist_entries", ["tenant_id"], unique=False)
    op.create_index(
        "idx_blocklist_source_tenant_id", "blocklist_sources", ["tenant_id"], unique=False
    )
    op.create_index(
        "idx_blocklist_source_tenant_name", "blocklist_sources", ["tenant_id", "name"], unique=True
    )
    op.create_index("idx_blocklist_stats_tenant_id", "blocklist_stats", ["tenant_id"], unique=False)
    op.create_index("idx_domains_tenant_domain", "domains", ["tenant_id", "domain"], unique=True)
    op.create_index("idx_domains_tenant_id", "domains", ["tenant_id"], unique=False)
    op.create_index("idx_features_tenant_id", "features", ["tenant_id"], unique=False)
    op.create_index("idx_feedback_tenant_id", "feedback", ["tenant_id"], unique=False)
    op.create_index("idx_metadata_tenant_id", "metadata", ["tenant_id"], unique=False)

    # Handle temporal_patterns index change (remove unique constraint from hour_of_day, day_of_week)
    op.drop_index("idx_temporal_hour_day", table_name="temporal_patterns")
    op.create_index(
        "idx_temporal_hour_day", "temporal_patterns", ["hour_of_day", "day_of_week"], unique=False
    )
    op.create_index(
        "idx_temporalpattern_tenant_hour_day",
        "temporal_patterns",
        ["tenant_id", "hour_of_day", "day_of_week"],
        unique=True,
    )
    op.create_index(
        "idx_temporalpattern_tenant_id", "temporal_patterns", ["tenant_id"], unique=False
    )

    # Add indexes for tld_reputation
    op.create_index("idx_tld_reputation_tenant_id", "tld_reputation", ["tenant_id"], unique=False)
    op.create_index(
        "idx_tld_reputation_tenant_tld", "tld_reputation", ["tenant_id", "tld"], unique=True
    )

    # Update other column types and constraints that were detected in the comparison
    op.alter_column("domains", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    op.alter_column(
        "domains",
        "domain",
        existing_type=sa.TEXT(),
        type_=sa.String(length=253),
        existing_nullable=False,
    )
    op.alter_column(
        "domains", "entropy", existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
    )
    op.alter_column(
        "domains", "risk_score", existing_type=sa.TEXT(), type_=sa.String(length=20), nullable=False
    )
    op.alter_column(
        "domains", "category", existing_type=sa.TEXT(), type_=sa.String(length=50), nullable=False
    )
    op.alter_column(
        "domains",
        "summary",
        existing_type=sa.TEXT(),
        type_=sa.String(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "domains", "is_anomaly", existing_type=sa.INTEGER(), type_=sa.Boolean(), nullable=False
    )
    op.alter_column(
        "domains", "anomaly_score", existing_type=sa.REAL(), type_=sa.Float(), nullable=False
    )
    op.alter_column(
        "domains",
        "analysis_source",
        existing_type=sa.TEXT(),
        type_=sa.String(length=30),
        nullable=False,
    )
    op.alter_column(
        "domains", "timestamp", existing_type=sa.TEXT(), type_=sa.DateTime(), nullable=False
    )
    op.alter_column(
        "domains",
        "created_at",
        existing_type=sa.TEXT(),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.create_index("idx_domains_category", "domains", ["category"], unique=False)
    op.create_index("idx_domains_created_at", "domains", ["created_at"], unique=False)
    op.create_index("idx_domains_domain", "domains", ["domain"], unique=False)
    op.create_index("idx_domains_is_anomaly", "domains", ["is_anomaly"], unique=False)
    op.create_index("idx_domains_risk_score", "domains", ["risk_score"], unique=False)

    op.alter_column(
        "features", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.alter_column("features", "length", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "features", "digit_ratio", existing_type=sa.REAL(), type_=sa.Float(), nullable=False
    )
    op.alter_column(
        "features", "vowel_ratio", existing_type=sa.REAL(), type_=sa.Float(), nullable=False
    )
    op.alter_column("features", "non_alphanumeric", existing_type=sa.INTEGER(), nullable=False)
    op.create_index("idx_features_domain_id", "features", ["domain_id"], unique=False)

    op.alter_column(
        "feedback", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )

    op.alter_column(
        "metadata", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True
    )
    op.alter_column(
        "metadata",
        "reason",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "metadata",
        "rule",
        existing_type=sa.TEXT(),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    op.alter_column(
        "metadata",
        "client",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.create_index("idx_metadata_domain_id", "metadata", ["domain_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes and constraints in reverse order
    op.drop_index(op.f("ix_tld_reputation_tenant_id"), table_name="tld_reputation")
    op.drop_index("idx_tld_reputation_tenant_tld", table_name="tld_reputation")
    op.drop_index("idx_tld_reputation_tenant_id", table_name="tld_reputation")
    op.drop_column("tld_reputation", "tenant_id")

    op.drop_index(op.f("ix_temporal_patterns_tenant_id"), table_name="temporal_patterns")
    op.drop_index("idx_temporalpattern_tenant_id", table_name="temporal_patterns")
    op.drop_index("idx_temporalpattern_tenant_hour_day", table_name="temporal_patterns")
    op.drop_index("idx_temporal_hour_day", table_name="temporal_patterns")
    op.create_index(
        op.f("idx_temporal_hour_day"),
        "temporal_patterns",
        ["hour_of_day", "day_of_week"],
        unique=True,
    )
    op.drop_column("temporal_patterns", "tenant_id")

    op.drop_index(op.f("ix_metadata_tenant_id"), table_name="metadata")
    op.drop_index("idx_metadata_tenant_id", table_name="metadata")
    op.drop_index("idx_metadata_domain_id", table_name="metadata")
    op.alter_column(
        "metadata",
        "client",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "metadata",
        "rule",
        existing_type=sa.String(length=500),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "metadata",
        "reason",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column("metadata", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_column("metadata", "tenant_id")

    op.drop_index(op.f("ix_feedback_tenant_id"), table_name="feedback")
    op.drop_index("idx_feedback_tenant_id", table_name="feedback")
    op.drop_column("feedback", "tenant_id")

    op.drop_index(op.f("ix_features_tenant_id"), table_name="features")
    op.drop_index("idx_features_tenant_id", table_name="features")
    op.drop_index("idx_features_domain_id", table_name="features")
    op.alter_column("features", "non_alphanumeric", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "features", "vowel_ratio", existing_type=sa.Float(), type_=sa.REAL(), nullable=True
    )
    op.alter_column(
        "features", "digit_ratio", existing_type=sa.Float(), type_=sa.REAL(), nullable=True
    )
    op.alter_column("features", "length", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("features", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_column("features", "tenant_id")

    op.drop_index(op.f("ix_domains_tenant_id"), table_name="domains")
    op.drop_index("idx_domains_tenant_id", table_name="domains")
    op.drop_index("idx_domains_tenant_domain", table_name="domains")
    op.drop_index("idx_domains_risk_score", table_name="domains")
    op.drop_index("idx_domains_is_anomaly", table_name="domains")
    op.drop_index("idx_domains_domain", table_name="domains")
    op.drop_index("idx_domains_created_at", table_name="domains")
    op.drop_index("idx_domains_category", table_name="domains")
    op.alter_column(
        "domains",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.alter_column(
        "domains", "timestamp", existing_type=sa.DateTime(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "domains",
        "analysis_source",
        existing_type=sa.String(length=30),
        type_=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        "domains", "anomaly_score", existing_type=sa.Float(), type_=sa.REAL(), nullable=True
    )
    op.alter_column(
        "domains", "is_anomaly", existing_type=sa.Boolean(), type_=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "domains",
        "summary",
        existing_type=sa.String(length=2000),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "domains", "category", existing_type=sa.String(length=50), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "domains", "risk_score", existing_type=sa.String(length=20), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "domains", "entropy", existing_type=sa.Float(), type_=sa.REAL(), existing_nullable=True
    )
    op.alter_column(
        "domains",
        "domain",
        existing_type=sa.String(length=253),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column("domains", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_column("domains", "tenant_id")

    op.drop_index(op.f("ix_blocklist_stats_tenant_id"), table_name="blocklist_stats")
    op.drop_index("idx_blocklist_stats_tenant_id", table_name="blocklist_stats")
    op.drop_column("blocklist_stats", "tenant_id")

    op.drop_index(op.f("ix_blocklist_sources_tenant_id"), table_name="blocklist_sources")
    op.drop_index("idx_blocklist_source_tenant_name", table_name="blocklist_sources")
    op.drop_index("idx_blocklist_source_tenant_id", table_name="blocklist_sources")
    op.drop_column("blocklist_sources", "tenant_id")

    op.drop_index(op.f("ix_blocklist_entries_tenant_id"), table_name="blocklist_entries")
    op.drop_index("idx_blocklist_tenant_id", table_name="blocklist_entries")
    op.drop_index("idx_blocklist_tenant_domain", table_name="blocklist_entries")
    op.create_index(
        op.f("ix_blocklist_entries_domain"), "blocklist_entries", ["domain"], unique=False
    )
    op.drop_column("blocklist_entries", "tenant_id")

    op.drop_index(op.f("ix_tenants_subdomain"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_api_key"), table_name="tenants")
    op.drop_index("idx_tenants_subdomain", table_name="tenants")
    op.drop_index("idx_tenants_api_key", table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
